name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - production
    paths:
      - "**.ts"
      - "**.js"
      - "**.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_ENVIRONMENT: ${{ github.ref_name == 'master' && 'staging' || 'production' }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - name: Type Check
        run: pnpm typecheck

      - name: Deploy to Cloudflare
        run: pnpm deploy
