name: Sentry Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - production
    paths:
      - "**.ts"
      - "**.js"
      - "**.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - name: Build
        run: pnpm tsc

      - name: Inject Debug IDS
        run: ./node_modules/.bin/sentry-cli sourcemaps inject --org $SENTRY_ORG --project $SENTRY_PROJECT ./dist

      - name: Upload source maps
        run: ./node_modules/.bin/sentry-cli sourcemaps upload --org $SENTRY_ORG --project $SENTRY_PROJECT ./dist

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        with:
          environment: ${{ github.ref_name == 'master' && 'staging' || 'production' }}
          ignore_empty: true
